brille24_customer_options_admin:
    resource: "@Brille24SyliusCustomerOptionsPlugin/Resources/config/app/routing/admin/customer_options.yml"

brille24_customer_option_groups_admin:
    resource: "@Brille24SyliusCustomerOptionsPlugin/Resources/config/app/routing/admin/customer_option_groups.yml"