# Overriding the Sylius resources
sylius_product:
    resources:
        product:
            classes:
                model: Brille24\SyliusCustomerOptionsPlugin\Entity\Product
sylius_order:
    resources:
        order_item:
            classes:
                model: Brille24\SyliusCustomerOptionsPlugin\Entity\OrderItem

# Defining new resources
sylius_resource:
    resources:
        brille24.customer_option:
            classes:
                model: Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOption
                interface: Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionInterface
                repository: Brille24\SyliusCustomerOptionsPlugin\Repository\CustomerOptionRepository
                form: Brille24\SyliusCustomerOptionsPlugin\Form\CustomerOptionType
            translation:
                classes:
                    model: Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionTranslation
                    interface: Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionTranslationInterface
                    form: Brille24\SyliusCustomerOptionsPlugin\Form\CustomerOptionTranslationType
        brille24.customer_option_group:
            classes:
                model: Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionGroup
                interface: Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionGroupInterface
                repository: Brille24\SyliusCustomerOptionsPlugin\Repository\CustomerOptionGroupRepository
                form: Brille24\SyliusCustomerOptionsPlugin\Form\CustomerOptionGroupType
            translation:
                classes:
                    model: Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionGroupTranslation
                    interface: Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionGroupTranslationInterface
                    form: Brille24\SyliusCustomerOptionsPlugin\Form\CustomerOptionGroupTranslationType
        brille24.customer_option_value:
            classes:
                model: Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionValue
                interface: Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionValueInterface
                form: Brille24\SyliusCustomerOptionsPlugin\Form\CustomerOptionValueType
            translation:
                classes:
                    model: Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionValueTranslation
                    interface: Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionValueTranslationInterface
                    form: Brille24\SyliusCustomerOptionsPlugin\Form\CustomerOptionValueTranslationType
        brille24.order_item_option:
            classes:
                model: Brille24\SyliusCustomerOptionsPlugin\Entity\OrderItemOption
                interface: Brille24\SyliusCustomerOptionsPlugin\Entity\OrderItemOptionInterface
                factory: Brille24\SyliusCustomerOptionsPlugin\Factory\OrderItemOptionFactory

        brille24.customer_option_validator_error_message:
            classes:
                model: Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\Validator\ErrorMessage
                form: Brille24\SyliusCustomerOptionsPlugin\Form\Validator\ErrorMessageType
            translation:
                classes:
                    model: Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\Validator\ErrorMessageTranslation
                    form: Brille24\SyliusCustomerOptionsPlugin\Form\Validator\ErrorMessageTranslationType
