# Overriding the Sylius resources
sylius_product:
    resources:
        product:
            classes:
                model: Brille24\CustomerOptionsPlugin\Entity\Product
sylius_order:
    resources:
        order_item:
            classes:
                model: Brille24\CustomerOptionsPlugin\Entity\OrderItem

# Defining new resources
sylius_resource:
    resources:
        brille24.customer_option:
            classes:
                model: Brille24\CustomerOptionsPlugin\Entity\CustomerOptions\CustomerOption
                interface: Brille24\CustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionInterface
                repository: Brille24\CustomerOptionsPlugin\Repository\CustomerOptionRepository
                form: Brille24\CustomerOptionsPlugin\Form\CustomerOptionType
            translation:
                classes:
                    model: Brille24\CustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionTranslation
                    interface: Brille24\CustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionTranslationInterface
                    form: Brille24\CustomerOptionsPlugin\Form\CustomerOptionTranslationType
        brille24.customer_option_group:
            classes:
                model: Brille24\CustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionGroup
                interface: Brille24\CustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionGroupInterface
                form: Brille24\CustomerOptionsPlugin\Form\CustomerOptionGroupType
            translation:
                classes:
                    model: Brille24\CustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionGroupTranslation
                    interface: Brille24\CustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionGroupTranslationInterface
                    form: Brille24\CustomerOptionsPlugin\Form\CustomerOptionGroupTranslationType
        brille24.customer_option_value:
            classes:
                model: Brille24\CustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionValue
                interface: Brille24\CustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionValueInterface
                form: Brille24\CustomerOptionsPlugin\Form\CustomerOptionValueType
            translation:
                classes:
                    model: Brille24\CustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionValueTranslation
                    interface: Brille24\CustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionValueTranslationInterface
                    form: Brille24\CustomerOptionsPlugin\Form\CustomerOptionValueTranslationType