sylius_product:
    resources:
        product:
            classes:
                model: Brille24\CustomerOptionsBundle\Entity\Product
                interface: Brille24\CustomerOptionsBundle\Entity\ProductInterface